/* eslint-disable @next/next/no-img-element */
import "./globals.css";
import ToastContainer from "@/components/toaster";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { signIn, signOut } from "next-auth/react";
import NavMenu from "@/components/nav-menu";

// import { useState } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" className="font-sans">
      <body>
        <main className="flex flex-col items-center justify-start p-4 min-h-screen">
          <div className="h-[5vh] w-full flex justify-between items-center">
            <h2 className="text-zinc-200">supathreads</h2>
            <div className="w-[60%] lg:w-[18%] md:w-[23%]">
              {session?.user ? (
                <NavMenu session={session} />
              ) : (
                <button onClick={() => signIn("github")}>Sign in</button>
              )}
            </div>
          </div>
          {children}
          <div className="h-[5vh] w-full flex justify-center items-center mt-4 text-left lg:w-[56%]">
            <p className="text-sm text-zinc-300 w-full">
              made with {`<3`} by{" "}
              <a
                href="https://twitter.com/_asheeshh"
                rel="noreferrer"
                target="_blank"
                className="text-teal-300 cursor-pointer"
              >
                ashish
              </a>
              {" ~ "}
              <a
                href="https://github.com/asrvd/supathreads"
                rel="noreferrer"
                target="_blank"
                className="text-teal-300 cursor-pointer"
              >
                source
              </a>
            </p>
          </div>
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
